import { Notification } from './types';

// Dummy notifications data with approval requests
export const dummyNotifications: Notification[] = [
    {
        id: 1,
        type: 'permission_request',
        title: 'Material Purchase Approval Required',
        message: 'Requesting approval for additional cement and steel purchase for Block A foundation work. Estimated cost: ₹2,50,000',
        projectName: 'Manthan Tower A',
        projectId: 1,
        senderName: 'Rajesh Kumar (Site Engineer)',
        timestamp: '2024-09-21T08:30:00Z',
        priority: 'high',
        isRead: false,
        requiresApproval: true,
        approvalStatus: 'pending',
        permissionType: 'material_purchase',
        requestAmount: 250000,
        requestDetails: 'Additional 50 bags of cement and 2 tons of steel bars required due to foundation depth revision.'
    },
    {
        id: 2,
        type: 'permission_request',
        title: 'Equipment Rental Approval',
        message: 'Need approval to rent JCB for excavation work. Daily rental: ₹8,000 for 3 days. Total: ₹24,000',
        projectName: 'Skyline Apartments B',
        projectId: 2,
        senderName: 'Priya Sharma (Site Engineer)',
        timestamp: '2024-09-21T07:15:00Z',
        priority: 'medium',
        isRead: false,
        requiresApproval: true,
        approvalStatus: 'pending',
        permissionType: 'equipment_rental',
        requestAmount: 24000,
        requestDetails: 'JCB required for basement excavation work. Expected completion in 3 days.'
    },
    {
        id: 3,
        type: 'work_remaining',
        title: 'Pending Electrical Work',
        message: 'Electrical wiring for floors 3-5 is pending. Current progress: 60%. Estimated completion: 3 days.',
        projectName: 'Green Valley Villas',
        projectId: 4,
        senderName: 'Sneha Reddy',
        timestamp: '2024-09-21T06:45:00Z',
        priority: 'medium',
        isRead: false,
    },
    {
        id: 4,
        type: 'permission_request',
        title: 'Overtime Work Authorization',
        message: 'Requesting approval for overtime work to meet project deadline. Additional labor cost: ₹15,000',
        projectName: 'Metro Plaza Complex',
        projectId: 3,
        senderName: 'Amit Patel (Site Engineer)',
        timestamp: '2024-09-20T16:20:00Z',
        priority: 'high',
        isRead: false,
        requiresApproval: true,
        approvalStatus: 'approved',
        permissionType: 'overtime_work',
        requestAmount: 15000,
        requestDetails: 'Need to work extra hours to complete concrete pouring before monsoon.'
    },
    {
        id: 5,
        type: 'material_alert',
        title: 'Low Steel Inventory',
        message: 'Steel bars inventory is running low. Current stock: 2 tons. Estimated requirement: 8 tons.',
        projectName: 'Tech Park Phase 1',
        projectId: 6,
        senderName: 'Kavya Nair',
        timestamp: '2024-09-20T14:30:00Z',
        priority: 'medium',
        isRead: false,
    },
    {
        id: 6,
        type: 'safety_alert',
        title: 'Safety Equipment Check',
        message: 'Monthly safety equipment inspection completed. 2 helmets need replacement.',
        projectName: 'Manthan Tower A',
        projectId: 1,
        senderName: 'Safety Inspector',
        timestamp: '2024-09-20T11:00:00Z',
        priority: 'low',
        isRead: false,
    },
    {
        id: 7,
        type: 'work_update',
        title: 'Foundation Work Completed',
        message: 'Foundation work for Block B has been completed successfully. Ready for next phase.',
        projectName: 'Manthan Tower A',
        projectId: 1,
        senderName: 'Rajesh Kumar',
        timestamp: '2024-09-19T16:00:00Z',
        priority: 'medium',
        isRead: true,
    },
    {
        id: 8,
        type: 'delay_warning',
        title: 'Weather Delay Alert',
        message: 'Heavy rainfall expected for next 3 days. Outdoor activities may be delayed.',
        projectName: 'Green Valley Villas',
        projectId: 4,
        senderName: 'Weather Service',
        timestamp: '2024-09-19T12:00:00Z',
        priority: 'high',
        isRead: true,
    },
    {
        id: 9,
        type: 'material_alert',
        title: 'Cement Delivery Scheduled',
        message: 'Cement delivery scheduled for tomorrow morning at 8 AM. Please ensure site access.',
        projectName: 'Skyline Apartments B',
        projectId: 2,
        senderName: 'Supply Manager',
        timestamp: '2024-09-19T10:30:00Z',
        priority: 'medium',
        isRead: true,
    },
    {
        id: 10,
        type: 'safety_alert',
        title: 'Safety Training Reminder',
        message: 'Monthly safety training scheduled for all workers this Friday at 2 PM.',
        projectName: 'Tech Park Phase 1',
        projectId: 6,
        senderName: 'Safety Officer',
        timestamp: '2024-09-18T15:45:00Z',
        priority: 'medium',
        isRead: true,
    },
];